### ISSUE TITLE
Recommend installing plugins in custom image?

### ISSUE THREAD

**Issue by timja** [jenkinsci/helm-charts#12]
Personally I never recommend installing plugins at runtime as the update center going down could stop you from being able to start your image.

Restarting a pod should always be safe.

Thoughts?

**Comment by torstenwalter** [comment]
Totally agree. We are always using images with pre-installed plugins. I prefer to have no external dependencies when deploying something in Kubernetes.

I also recommend to pin version so that one knows what will be part of the image.

For the chart if could make sense to still allow downloading plugins on startup. This prevents us from having to build a custom image whenever a new Jenkins version is released. It also makes it easy for people to add plugins.

Availability of the update center is an issue. That's something we also noticed during ci tests of the chart. For initial deploy there is not much we can do about it. What we could do to prevent it from being an issue during restarts is to check if we have already downloaded the plugins specified and if so just skip that step.

**Comment by trey2001** [comment]
I need to create an image because of the redirects and a corporate proxy config. How do you do it from the chart so it's pulling from somewhere like ECR in AWS?


> Totally agree. We are always using images with pre-installed plugins. I prefer to have no external dependencies when deploying something in Kubernetes.
> 
> I also recommend to pin version so that one knows what will be part of the image.
> 
> For the chart if could make sense to still allow downloading plugins on startup. This prevents us from having to build a custom image whenever a new Jenkins version is released. It also makes it easy for people to add plugins.
> 
> Availability of the update center is an issue. That's something we also noticed during ci tests of the chart. For initial deploy there is not much we can do about it. What we could do to prevent it from being an issue during restarts is to check if we have already downloaded the plugins specified and if so just skip that step.

**Comment by torstenwalter** [comment]
The chart does not support building a custom image.

Benefit of having a custom image is that it does not change. If this chart would build the image then it would change.

https://github.com/jenkinsci/docker explains how to build a custom image.

Once you built and published your custom image to a registry you can configure the his chart to use it.

```yaml
master:
  image: "my-registry/my-jenkins"
  tag: "my-tag"
```
