### ISSUE TITLE
Init container "copy-default-config" fails with "cp: cannot stat '/usr/share/jenkins/ref/plugins/*': No such file or directory"

### ISSUE THREAD

**Issue by leopaul36** [jenkinsci/helm-charts#140]
**Describe the bug**
The installation of the chart with all the default values fails to correctly install the plugins. The init container `copy-default-config` fails with:

```
kubectl logs jenkins-6579c7b576-rcm9q copy-default-config

applying Jenkins configuration
disable Setup Wizard
download plugins
Plugin workflow-aggregator:2.6 depends on workflow-job:2.40, but there is an older version defined on the top level - workflow-job:2.39
copy plugins to shared volume
cp: cannot stat '/usr/share/jenkins/ref/plugins/*': No such file or directory
finished initialization
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
2.17.1

**What happened**:
Jenkins is deployed without any plugins

**What you expected to happen**:
Jenkins being installed with all the provided plugins

**How to reproduce it** (as minimally and precisely as possible):
`helm install jenkins jenkins/jenkins`

**Anything else we need to know**:

It works correctly with the `2.17.0` version of the chart.

**Comment by Andrei-Stepanov** [comment]
@torstenwalter 
Between 2.17.0 and 2.17.1 only 1 commit:

https://github.com/jenkinsci/helm-charts/compare/jenkins-2.17.0...jenkins-2.17.1

**Comment by oisis** [comment]
@leopaul36  @Andrei-Stepanov

You have probably issue with plugins downloads. The error tells that there is no plugins files in directory /usr/share/jenkins/ref/plugins/ so copy command(cp) fails. Please check if helm is properly configured(installPlugins and additionalPlugins), second idea is you are behind proxy/firewall so jenkins-plugin-cli cannot download plugins because of issue with:
- JENKINS_UC
- proxy settings
- OpenSSL certs and java

**Comment by Andrei-Stepanov** [comment]
Snippet from user values file: 
This perfectly works for jenkins-2.17.0
/usr/share/jenkins/ref/plugins/ is empty in jenkins-2.17.1
Same environment:  jenkins-2.17.0 -- can pass initialization step.  jenkins-2.17.1 - cannot pass.

```
---
master:a
  jenkinsUrl: "https://<CUT>"
  additionalPlugins:
    - 'jms-messaging'
    - 'oic-auth'
    - 'ircbot'
    - 'matrix-auth'
    - 'throttle-concurrents'
  adminPassword: <CUT>
...
```

**Comment by thogaw** [comment]
Same Issue with Helm-Chart Version 2.18.0 .... 2.17.0 works as expected.

**Comment by oisis** [comment]
@thogaw 
In first message i see something like:
`Plugin workflow-aggregator:2.6 depends on workflow-job:2.40, but there is an older version defined on the top level - workflow-job:2.39`
which means jenkins-plugin-cli could not resolve dependencies and that is why failed, so this is the root cause in this case.

**Comment by thogaw** [comment]
OK, then the Helm-Chart should be updated with the correct versions of predefined plugins. Since we tried to install with standard plugins (installPlugins-Directive in values.yaml)

**Comment by thogaw** [comment]
The following combination of plugins seems to work as expected:

`
master.installPlugins:
  - kubernetes:1.25.7
  - workflow-job:2.40
  - workflow-aggregator:2.6
  - credentials-binding:1.24
  - git:4.2.2
  - configuration-as-code:1.43
`

**Comment by oisis** [comment]
IMHO variable installPlugins should be empty list.

**Comment by torstenwalter** [comment]
> IMHO variable installPlugins in example values.yaml should be an empty list.

That would not work as the `kubernetes` and `configuration-as-code` plugins are needed for the configuration to work.

The error is perfectly described in the bug description:

```
applying Jenkins configuration
disable Setup Wizard
download plugins
Plugin workflow-aggregator:2.6 depends on workflow-job:2.40, but there is an older version defined on the top level - workflow-job:2.39
copy plugins to shared volume
cp: cannot stat '/usr/share/jenkins/ref/plugins/*': No such file or directory
finished initialization
```

> Plugin workflow-aggregator:2.6 depends on workflow-job:2.40, but there is an older version defined on the top level - workflow-job:2.39

The problem is that `workflow-job `is specified in plugin list. It's a dependency of `workflow-aggregator` plugin so it would be better to let the plugin manager figure out which dependency version to download.

Another issue I see is that the script continues. In my opinion it would be better to fail the init container and not to start Jenkins at all.
