### ISSUE TITLE
VALUES_SUMMARY.md linked to local which shown incorrectly in helm.sh

### ISSUE THREAD

**Issue by larrycai** [jenkinsci/helm-charts#27]
https://hub.helm.sh/charts/jenkinsci/jenkins the `VALUES_SUMMARY.md` points to local, it shall be sth like `https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md`

**Comment by torstenwalter** [comment]
Artifacthub does not render the link at all:
![image](https://user-images.githubusercontent.com/1743774/92222902-fcfef700-ee9f-11ea-832e-b9c4ca208afd.png)

I''d like to avoid having the complete URL as it makes editing locally harder and is also not really convenient if you make changes to a branch is it would always point to the `main` branch.

@scottrigby Do you have an idea how we should format it so that it appears correctly in artifacthub and hub.helm.sh?

**Comment by scottrigby** [comment]
This is interesting... I'm not sure why I didn't notice this before now.

The hubs render a chart's Readme by downloading and unpacking its linked package, not directly from GitHub source (or wherever the source files are), because a helm repo doesn't require making source files public and some don't (a helm repo is just an index file, with metadata including the chart version tarball URLs. The tarballs can be served from an object storage service like s3, hosted on any http server, etc. for that reason the hubs then add the chart's raw, unpacked Readme to an API endpoint response for the fronted to render the markdown in the hub. It doesn't also send all the possible files along in the response in case the readme links to one of them.

So this is an interesting problem. For now let's talk any Artifact Hub, as no further work is going into Helm Hub before we move fully to Artifact Hub. Initial thoughts:

- Maybe Artifact Hub could somehow scan the readme after unpacking the chart and follow all the readme relative links (to allowable file types like md txt etc), and if they are within the chart package itself (not `../` or higher, which it wouldn't have access to) it could add those files to the API response as well so they can also be rendered on the hub?
- Or maybe better, Artifact Hub could provide a way for helm repo maintainers to optionally specify a source URL, so relative links in the readme can be expanded to their full URL equivalent?

**Comment by scottrigby** [comment]
We're discussing this here https://github.com/artifacthub/hub/issues/629 This is an issue for all relative links in the hubs until resolved upstream.
