### ISSUE TITLE
please make javaOpts value from a configmap

### ISSUE THREAD

**Issue by latituder** [jenkinsci/helm-charts#275]
**Is your feature request related to a problem? Please describe.**
javaOpts env always need to be changed during operation. current helm chart make javaOpts a string, so if we need to add/remove a parameter from javaOpts, we need to update the helm chart.
It will bring convenience, if javaOpts value can be read from a configmap, then people can directly change the cm and restart the pod to make it take effect.

**Describe the solution you'd like**
Create a configmap, and store the javaOpts values in the cm;
everytime jenkins controler startup, it read the cm and inject it to be the javaOpts env;

**Describe alternatives you've considered**
also can be a k8s secret

**Additional context**

**Comment by torstenwalter** [comment]
I don't get you point. Java opts is defined in https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L158-L160
You can configure it by setting `controller.javaOpts`.

**Comment by latituder** [comment]
thanks for reply.
Yes, but if I always need to change the JavaOption, then it's better to save the JavaOption into a configmap.
in this case, people only change the configmap and restart the pod. no need to exec helm

**Comment by torstenwalter** [comment]
Even if you do it like that you would run into the problem that during the next run of helm the ConfigMap would be overwritten and you change is lost.
You are basically asking that a helm chart should support managing things outside of helm. If we would not update the ConfigMap based on the `values.yaml` then other people would run into problems, because they expect that there changes in `values.yaml` are reflected in the ConfigMap.

If you want to make changes without using helm then simply rendering all the manifests (`helm template ...`) could be an option and from then on update files manually.
