### ISSUE TITLE
When httpsKeyStore is enabled, Jenkins fails to start

### ISSUE THREAD

**Issue by hak33m16** [jenkinsci/helm-charts#364]
**Describe the bug**
When httpsKeyStore is enabled, Jenkins fails to start and emits a stacktrace

**Version of Helm and Kubernetes**:

```console
$ helm version
Helm Version: version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
3.3.14

**What happened**:
Experienced an exception with the following stacktrace at startup:
```
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2021-05-14 14:08:46.883+0000 [id=1]     INFO    org.eclipse.jetty.util.log.Log#initialized: Logging initialized @607ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-05-14 14:08:47.032+0000 [id=1]     INFO    winstone.Logger#logInternal: Beginning extraction from war file
2021-05-14 14:08:47.063+0000 [id=1]     WARNING o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2021-05-14 14:08:47.129+0000 [id=1]     INFO    winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:226)
        at winstone.Launcher.<init>(Launcher.java:180)
        at winstone.Launcher.main(Launcher.java:369)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:375)
        at Main.main(Main.java:151)
Caused by: winstone.WinstoneException: No SSL key store found at "/var/jenkins_keystore/keystore.jks"
        at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
        at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:53)
        at winstone.Launcher.spawnListener(Launcher.java:220)
        ... 8 more
2021-05-14 14:08:47.131+0000 [id=1]     SEVERE  winstone.Logger#logInternal: Container startup failed
winstone.WinstoneException: No SSL key store found at "/var/jenkins_keystore/keystore.jks"
        at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
        at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:53)
        at winstone.Launcher.spawnListener(Launcher.java:220)
Caused: java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
        at winstone.Launcher.spawnListener(Launcher.java:226)
        at winstone.Launcher.<init>(Launcher.java:180)
        at winstone.Launcher.main(Launcher.java:369)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at Main._main(Main.java:375)
        at Main.main(Main.java:151)

```

**What you expected to happen**:
For it to successfully start

**How to reproduce it**:

values.yaml
```
controller
  httpsKeyStore:
    enable: true
```

```
helm install my-release jenkins/jenkins --version 3.3.14 --values values.yaml
```

This comment seemed to have some good insight as to why: https://github.com/jenkinsci/helm-charts/issues/226#issuecomment-835263549

I experienced this while upgrading from chart v2.6.5 to latest, and I'm on Jenkins v2.277.4 (no change). From what I can tell by comparing the values.yaml between 2.6.5 and latest, it doesn't seem like I should've had to change anything for this to work, so I'm inclined to believe the issue may be what @richardkhardy was referring to

**Comment by MilanovBorislav** [comment]
I don't know if this is the right place but this line may be revisited
           ` {{- $httpsJKSFilePath :=  printf "%s/%s" .Values.controller.httpsKeyStore.path .Values.controller.httpsKeyStore.fileName }}`[link](https://github.com/jenkinsci/helm-charts/blob/7273190b006c11fef99432c50eee176d8a4b08f2/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L228)
It create  `- mountPath: /var/jenkins_keystore/keystore.jks`  not  `- mountPath: /var/jenkins_keystore` as we may expect. In this case  `- --httpsKeyStore=/var/jenkins_keystore/keystore.jks` is broken because the path shoud be 
`- --httpsKeyStore=/var/jenkins_keystore/keystore.jks/keystore.jks` 
Something like `{{- $httpsJKSFilePath :=  printf "%s" .Values.controller.httpsKeyStore.path }}` will fix the mount path.

**Comment by timja** [comment]
care to provide a PR with a test?

**Comment by MilanovBorislav** [comment]
Sure I will try.

**Comment by julianxhokaxhiu** [comment]
Sorry to jump on this issue but basically #503 reverts #391 which was the PR I did to fix it because exactly, the path only doesn't mount as expected because the filename is reflected nowhere, which brings the code basically to where it was before #391.

Now, has someone really test this because the last time I had to test it myself and I to create #391 and without that patch it was not working. How could it be it works now with #503?

Any clarification is appreciated. Thanks.

**Comment by timja** [comment]
Shouldn't file name just be dropped and path is the full path to the file?

do we need the file name at all?

**Comment by julianxhokaxhiu** [comment]
The main issue I faced is that this line actually attempts to use the file declared in the path with that defined `fileName` ( https://github.com/jenkinsci/helm-charts/blob/cab91d9a1c93dd0fa276b4eef6dbd588f137b6f5/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L165 ) but in fact the file will never have that name, because in the secret the file is named like this: https://github.com/jenkinsci/helm-charts/blob/cab91d9a1c93dd0fa276b4eef6dbd588f137b6f5/charts/jenkins/templates/secret-https-jks.yaml#L17

Therefore, we either need to drop entirely the `fileName` logic and just allow to customize the path, or find a way to link these two things somehow. I agree also that my PR was uncomplete at the moment I created it because I forgot to path the L165 in the statefulset yaml, as it should have pointed to `/var/jenkins_keystore/keystore.jks/jenkins-jks-file`.

So I think dropping `fileName` just makes sense, it practically useless and we could just hardcode the filename in the secret as well as in the statefulset yaml. All we can allow to customize is the path, which makes sense.

**Comment by torstenwalter** [comment]
Could you re-check? I think the filename was already dropped.

**Comment by julianxhokaxhiu** [comment]
> Could you re-check? I think the filename was already dropped.

Links are from the master branch so unless I'm missing something here, I'm not sure what am I supposed to check.

**Comment by timja** [comment]
Isn't the mount path just the directory to mount and above is the file name?

Previous PR changed the path to not include file name in mount which I think is right?

**Comment by julianxhokaxhiu** [comment]
> Isn't the mount path just the directory to mount and above is the file name?
> 
> Previous PR changed the path to not include file name in mount which I think is right?

it is right but the code will still fail as soon as you enable the httpsKeyStore mount, because the statuful set will pass this argument to Jenkins
```sh
--httpsKeyStore=/var/jenkins_keystore/keystore.jks
```
instead of
```sh
--httpsKeyStore=/var/jenkins_keystore/jenkins-jks-file
```
which is where the file is really existing.

**Comment by timja** [comment]
why isn't it at the first one?

**Comment by julianxhokaxhiu** [comment]
> why isn't it at the first one?

Because of how Kubernetes mounts secrets. The `key` value of your data attribute, will become the `fileName` so, you can customize it as much as you want in `values.yaml` but if the httpsKeyStore `Secret` will not inherit that value as `key` of the relative data file, then it's practically useless.

Here, as mentioned before, it's hardcoded to `jenkins-jks-file` ( https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/secret-https-jks.yaml#L17 )

**Comment by julianxhokaxhiu** [comment]
> why isn't it at the first one?

Nevermind, I noticed now that the yaml file here https://github.com/jenkinsci/helm-charts/blob/cab91d9a1c93dd0fa276b4eef6dbd588f137b6f5/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L396 mounts it correctly. So yeah, you're right, should be fine now. My bad. Thanks!
