### ISSUE TITLE
Use docker from host 

### ISSUE THREAD

**Issue by chatchaisi** [jenkinsci/helm-charts#382]
How can I mount and volume docker from host to use in jenkins pipeline ?

Thank you for help me.

**Comment by mcandre** [comment]
Related: https://github.com/jenkinsci/helm-charts/issues/221

**Comment by mcandre** [comment]
Related: https://stackoverflow.com/questions/51681713/jenkins-helm-docker-not-found-when-try-to-run-a-test

**Comment by mcandre** [comment]
Related: https://github.com/helm/charts/issues/7002

**Comment by mcandre** [comment]
Two minor steps originally enabled Docker-in-Docker support for Jenkins jobs:

1. Install the Docker package into a Jenkins worker pod template image.
2. Wire up the Docker socket.

```groovy
podTemplate(yaml: """
---
apiVersion: "v1"
kind: "Pod"
spec:
  containers:
    - name: "test"
      image: "test"
      imagePullPolicy: "Always"
      tty: true
      command: ["/bin/cat"] # Fix worker infinite recursion
      volumeMounts:
      - mountPath: "/var/run/docker.sock"
        name: "docker-socket-volume"
      securityContext:
        privileged: true
        runAsUser: 0
      restartPolicy: "Never"
  volumes:
  - name: "docker-socket-volume"
    hostPath:
      path: "/var/run/docker.sock"
      type: "File"
""") {
    node(POD_LABEL) {
        stage('Deploy') {
            // ...
        }
    }
}
```

Unfortunately, this no longer works with the latest Jenkins Helm chart. I keep getting these warnings:

```console
[Warning][jenkins/auth-service-migrate-jenkins-2-gzn1r-nzc6r-sg9gs][FailedMount] MountVolume.SetUp failed for volume "docker-socket-volume" : hostPath type check failed: /var/run/docker.sock is not a file
```

They should really be treated as errors, but they are presented as warnings. And the job will get stuck like that indefinitely, instead of quickly terminating.

Not sure why Docker in Docker is no longer working for me with the Jenkins Helm chart. I tried explicitly adding the `jenkins` UNIX user account to the `docker` group, but that does not help.
