### ISSUE TITLE
podtemplate reset when jenkins pod restart

### ISSUE THREAD

**Issue by wjstk16** [jenkinsci/helm-charts#440]
Hi all,

I installed it using Jenkins Helm Chart version 3.5.9. Even though I set up pv and installed it, there is a problem that when the pod is restarted, the setup for podtemplate is reset. Settings other than podtemplate are not reset.
I want to know why this problem is happening. Where are podtemplate settings stored?

Thanks.

**Comment by torstenwalter** [comment]
Works as designed. pod templates are managed by Configuration as Code plugin. Therefor whenever configuration as code is reloaded (what happens when you restart Jenkins) manual changes there are overridden. 

Have a look at https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#configuration-as-code and https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#adding-custom-pod-templates how to use JCasC.

The defaults are defined here: https://github.com/jenkinsci/helm-charts/blob/7a9b7c160d2f674a6ecc21cd4d7a1e53c073aad0/charts/jenkins/templates/_helpers.tpl#L101-L201
