### ISSUE TITLE
On start, CasC configuration is reloaded way too often

### ISSUE THREAD

**Issue by Cytrian** [jenkinsci/helm-charts#868]
### Is your feature request related to a problem? Please describe

In our setup I experience the following issue: Upon restart of Jenkins, the config-reload sidecar sends up to 28 configuration-reload requests to the Jenkins process. We have 12 casc-configmaps.
So, for _each_ ConfigMap, the config file is being created, a reload-request sent to Jenkins, which reloads all configuration files.

So the first config file will be reloaded 12 times (In our case probably even more because of some other issues).

The main issue that I have with this, that it takes time and is unnecessary work.

### Describe the solution you'd like

I propose to run kiwigrid additionally as an initContainer, so that all casc configuration files are in place before Jenkins even starts.
Just run the kiwigrid with `METHOD="LIST"` once and that's it. That makes restarting a lot easier and faster, I hope.

**Comment by justusbunsi** [comment]
Just found this issue. Out of curiosity, do you experience larger memory peaks during these reloads? I do, or at least I think it could be related to that issue. That's why I ask.

**Comment by dominykas** [comment]
> The main issue that I have with this, that it takes time and is unnecessary work.

There's a bit more to it than wasted work.

In our case, this results in weird race conditions during start up and random failures depending on the order the files arrive in - e.g. you could get random failures due to some credentials missing in Kubernetes, or you could get serialization errors (something about nulls and XML?), presumably due to config being incomplete.

These errors can result in crashes and restarts. In our case, it can take 3-4 restarts before Jenkins actually finally comes up. This is of course very much undesireable, because of prolonged downtime (missing webhooks, etc). But there's more - when Jenkins crashes during startup, it sometimes wipes the build queue.

I also just had the idea that maybe running config-reload as an init container could help, so I'll just try that and might potentially PR, if it works.

**Comment by dominykas** [comment]
Quick testing is showing me that things are a LOT more stable if I run `config-reload` as an `initContainer` (I do intend to keep it around as a sidecar as well).

Will probably formalize the solution and try it out a little longer, and might PR if that's acceptable?
